name: maceManager
version: '1.1'
main: me.sazawa.maceManager.MaceManager
api-version: '1.21'
authors: [sazawa]
description: a plugin to manage event-won maces

permissions:
  maceManager.bypass:
    default: op
  maceManager.createMace:
    default: op

commands:
  createMace:
    description: Create a mace with lore.
    usage: /createMace
    permission: maceManager.createMace